= MicroProfile Showcase Application

== General information

The application consists of several Microservices and a Web-Application managing a conference :

* `microservice-schedule` : Schedule of the conference
* `microservice-session` : Sessions of the conference
* `microservice-speaker` : Speakers of the conference
* `microservice-vote` : Votes for each session
* `web-application` : Frontend Angular2 | Bootstrap4

The WebApp is a direct subscriber to the individual Microservices.
This means that there is no aggregator / middle-man application.
The WebApp itself provides a known relative EndPoint microservice that enables the lookup of
URLs to the other services.

The sample is a version of the MicroProfile sample application, designed to run all the services on Open Liberty.

If you would like to participate in the MicroProfile community effort to advance EE then by all
means feel free to join us on the following sites:

http://microprofile.io/[Microprofile.io]
- The community landing site.

https://groups.google.com/forum/#!forum/microprofile[Google+ Microprofile groups]
- Public discussion lists (We do not have private lists).

https://waffle.io/microprofile/microprofile-conference/join[Kanban board]
- A nice Kanban integration for our GitHub issues.

https://github.com/microprofile[All source code]
- https://www.apache.org/licenses/LICENSE-2.0[Apache Licence V2] project OSS code.

== Technologies

* Java
* MicroProfile
* JAX-RS 2.0 / JSON-P 1.0 / CDI 1.1

== Quickstart - Run all services and UI in separate runtimes

To run all the services on individual Open Liberty servers:

----
mvn clean package -P start
----

To view the Web application, open a browser at http://localhost:8080/

To build each service but not start the individual servers:

----
mvn package
----

To clean up the build, including stopping the individual servers:

----
mvn clean
----



== Common problems/bugs

=== NPM issues

The web-application project uses the *com.github.eirslett:frontend-maven-plugin* to download
and install all node and npm requirements.
Sometimes this may fail if console permissions are not permissive enough.

In such cases you will have to manually install some reqiurements:

<1> Download and install node: https://nodejs.org/en/download/current/

<2> Install npm manually:

----
cd web-application/src/main/static
npm install npm
npm install typings --global
typings install --global
----

== Original source

This samples is based of the MicroProfile Conference demo at:

* https://github.com/microprofile/microprofile-conference


